# Generated by Django 2.1.2 on 2018-10-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '首页轮播商品', 'verbose_name_plural': '首页轮播商品'},
        ),
        migrations.AlterModelOptions(
            name='goodscategorybrand',
            options={'verbose_name': '宣传品牌', 'verbose_name_plural': '宣传品牌'},
        ),
    ]
