# Generated by Django 2.1.2 on 2018-10-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20181018_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '订单内商品项', 'verbose_name_plural': '订单内商品项'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '订单基本信息', 'verbose_name_plural': '订单基本信息'},
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='nonce_str',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='随机加密串'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='pay_type',
            field=models.CharField(choices=[('alipay', '成功'), ('wechat', '微信')], default='alipay', max_length=10, verbose_name='支付类型'),
        ),
    ]
